# world setting
images_save_dir: ./output_dataset/map
annotions_save_dir: ./output_dataset/annotation
logs_pic_dir: ./output_dataset/logs
annotions_file_name: room_ctr_dataset_1.json
info_file_name: dataset_info_1.json



json_dir: ./input_data/label_data/
map_id_set: ./input_data/label_list/label_floor_plans.txt
visualization_enable: 0


meter2pixel: 20 # X pixel =1 meter
mode: 0  # 0 for exploration mode, 1 for navigation mode
start_order: 0
epoch: 0
# obstacle:
#   number: 0 # number of obstacle added to the world
#   size: # size of obstacle added in meter, length/diameter
#     min: 0.5 
#     max: 2

obstacle:
  number: 30 # number of obstacle added to the world
  size: # size of obstacle added in meter, length/diameter
    min: 0.05 
    max: 3

# robot setting
robotRadius: 0.2 # robot radius in meter
stepLength:
  linear: 0.3 # robot linear movement in each step in meter
  angular: 10 # robot angular movement in each step in degree
startPose: # robot starting pose [y;x;theta] in meter in world coord with center as origin | theta: angle to the x-axis
  x: 0
  y: 0
  theta: 0
resetRandomPose: 1 # flag of whether randomly set robot init pose ar each reset | if 0, robot reset to startPose at each reset

# # laser setting
# laser:
#   range: 5 # laser range in meter
#   fov: 180 # laser field of view in degree
#   resolution: 0.7 # laser rotation resolution in degree
#   noiseSigma: 0 # sigma of Gaussian distribution of laser noise

# laser setting
laser:
  range: 5 # laser range in meter
  fov: 180 # laser field of view in degree
  resolution: 0.7 # laser rotation resolution in degree
  noiseSigma: 0.3 # sigma of Gaussian distribution of laser noise

# # slam setting
# slamError:
#   linear: 0  # slam linear registration error in pixel
#   angular: 0 # slam rotational registration error in degree

# slam setting
slamError:
  linear: 0.5  # slam linear registration error in pixel
  angular: 0.2 # slam rotational registration error in degree
  
# state setting
stateSize: # state size in meter
  x: 4 # state in pixel = x * meter2pixel
  y: 4
